# Generated by Django 5.2.5 on 2025-08-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
            ],
        ),
    ]
